default: true

MD013: false    # Line length
MD014: false    # Dollar signs used before commands without showing output
MD042: false    # No empty links
MD024: false    # Multiple headings with the same content
